### PR TITLE
Integration test runner, issue #50

### PR DESCRIPTION
**Pull request by CarstenAgerskov**
The documentation I wrote on the integration test runner. I did not create any link from the main documentation to this page, because I don't know how you want the overall structure. Furthermore, I expect you want to add or change the text to better target your needs.

### CODE REVIEW

**Comment by KathyReid** [comment]
Thanks so much for this documentation @CarstenAgerskov, I really appreciate it. @forslund is giving me a run through of `autotest` next Tuesday, and then I will review this PR, and link the documentation from the main page. 

Kind regards, Kathy

**Comment by CarstenAgerskov** [comment]
You are welcome. Yes, Åke made some changes to the code, you may want to verify my text is still valid :)

**Comment by KathyReid** [comment]
I've made some changes to this file - it was very, very good - they are minor formatting changes. @forslund also kindly walked me through the Integration Test Runner - thank you!

Before merging this PR, I would like to add; 

* A list of the `assert` options such as `StartsWith`, `EndsWith` and so on
* Something around test _coverage_ - can we report on the code coverage at all? The reason I ask is that it might be possible to test *some* of the **Intents**, and make it look like everything is passing, when the test coverage is minimal. Code coverage % gives the Skill Reviewer some assurance that the tests are well-written. 

One other, possibly unrelated question, is about the _branching_ of the `mycroft-skills` repo. We haven't documented at all how we're going to handle this branching (unless @penrods possibly has something I haven't seen yet). I think we should release both the Integration Test Runner and Skill Branching at the same time because they are dependent - at least to some extent. 

What are your thoughts? Should we hold releasing this documentation until we have something documented around Skill Branching?

**Comment by CarstenAgerskov** [comment]
Thanks. Let me give a short answer. (I have a long answer as well, and some experience writing test cases for a major upgrade of the cows list, that I am currently working on, if anyone is interested:)

The assert options are currently limited to little more than those needed to transform the json to rule format. However, it is very easy to put in more if needed:
equal
notEqual
endsWith
match
and 
or

I see the assert mostly as an expert option. General things to test should probably be added as test case json keywords. The internal rule format serves as a convenient way to add more json keywords, it decouples keywords from a more generalized message validation. (But it was easy to open for general use.)

The test runner looks at the bus, unfortunately it does not know what happens inside the skill, unless it is reflected on the bus. The test_all_skills.py test that all intents are activated at least once. That is currently the only metric for coverage. But I do have some ideas for future options, that may or may not be viable depending on how the test runner is used.

I have no opinion on whether to hold the release or not :)

**Comment by CarstenAgerskov** [comment]
Just saw your last commit. You are right of cause, the emitter is mocked, you can get coverage. Forget what I wrote about the test runner looking at the bus.

**Comment by KathyReid** [comment]
I'm making the decision to merge this PR - we can do the `branching` documentation later on.

**Pull request merged**
