### PR TITLE
Comment out TODO

### PR DESCRIPTION
**Pull request by ofek**

### CODE REVIEW

**Comment by krisgesling** [comment]
Hi Ofek, thanks for the contribution!

We appreciate your support for the project. To protect you, the project, and those who choose to use Mycroft technologies in systems they build, we ask all contributors to sign a Contributor License Agreement. You only need to do this once, so any future contributions you make can be merged quickly and easily.

This agreement clarifies that you are granting a license to the Mycroft Project to freely use your work.  Additionally, it establishes that you retain the ownership of your contributed code and intellectual property.  As the owner, you are free to use your code in other work, obtain patents, or do anything else you choose with it.

**For more info and to get started head to: https://mycroft.ai/cla/**

If you have any questions, please let me know :slightly_smiling_face:

**Comment by ofek** [comment]
@krisgesling Done 😄

**Comment by penrods** [comment]
I resent your CLA.  In order for the Github approval/association to be work, the CLA needs to list your username (ofek), not the associated email.  Thanks for your interest and understanding about this!

**Comment by ofek** [comment]
@penrods Fixed, thanks!

**Comment by krisgesling** [comment]
Excellent, thanks again Ofek!

We really value your input into our documentation, so please let me know if you have any questions about other pages or topics you are looking at.

**Comment by ofek** [comment]
Will do, thanks!

**Pull request merged**
