### PR TITLE
Significant rewrite of the Picroft documentation for the Raspbian Stretch Lightning version

### PR DESCRIPTION
**Pull request by KathyReid**
This is a significant rewrite of the Picroft documentation, and "folds in" several pages of documentation to reduce our documentation "surface area", including: 

* https://mycroft.ai/documentation/picroft/picroft-audio/
* https://mycroft.ai/documentation/picroft/picroft-automatic-update/
* https://mycroft.ai/documentation/picroft/picroft-image/
* https://mycroft.ai/documentation/picroft/picroft-wifi/

When this PR is merged, several redirects will need to be put in place for these pages so that they don't 404. 

In particular, the person who reviews this PR should double check; 

* whether the "sequence" of steps is correct for the Lightning preview
* whether any of the instructions are incorrect for Lightning preview

_Please note that I haven't created a Table of contents using `markdown-toc` for this page - I am anticipating that there will be edits to this file before it is merged._

### CODE REVIEW

**Comment by forslund** [comment]
Just starting here but I think in the bluetooth audio section the part about changing the port can be removed. the picroft doesn't launch the Mark-1 enclosure anymore and will not use the port config at all.

**Comment by KathyReid** [comment]
Thanks for your feedback @forslund - I removed the Bluetooth audio section in one of the commits because I don't think it's relevant any more with the guided setup. Does that make sense?

**Comment by forslund** [comment]
Aha, the file preview showed the old file not the new one. Sorry

**Comment by KathyReid** [comment]
inga problem ;-)

**Comment by penrods** [comment]
I've lightly reviewed and will merge it for now, as there are many now-misleading things in the old doc that this certainly corrects.  Anything that needs to be altered further can be pulled in with a later PR.

**Pull request merged**
