### PR TITLE
Update picroft-wifi.md

### PR DESCRIPTION
**Pull request by Timmmy001**
Add information from WPS and encrypting local wifi key.

### CODE REVIEW

**Comment by KathyReid** [comment]
Hi @Timmmy001 thank you for providing such helpful information. In order to maintain compliance with our open source licenses, we need to ensure that each Contributor provides a Contributor License Agreement - https://mycroft.ai/cla. Could you please request and fill out a CLA?

Kind regards, 
Kathy

**Comment by Timmmy001** [comment]
Hello Kathy,

is filled.


Kind regards, 
Timmmy
(tomhb777@googlemail.com)

----------------------------------------------------------------------------

**Comment by penrods** [comment]
Timmmy,

I just noticed this was stalled.  It looks like the CLA request never made it to/through out system -- might have been related to some issues we've noticed with the CLA email notifier that feeds the system.  I went ahead and am manually sending the HelloSign document request to you as an Individual Contributor using the email you listed above.

Sorry about the delay, let me know if you have any questions.

   - Steve

**Comment by KathyReid** [comment]
Am deliberately holding off on this PR as Picroft is scheduled to undergo some major updates this week, which will likely change the way that it handles WiFi.

**Comment by penrods** [comment]
Given the reworked mechanism in Picroft today, shall we close this one?

**Comment by KathyReid** [comment]
Agreed, good catch.

**Pull request closed without merging**
